set(_AMENT_PACKAGE_NAME "us_msg")
set(us_msg_VERSION "0.0.0")
set(us_msg_MAINTAINER "mateo-drr <mateodrr@gmail.com>")
set(us_msg_BUILD_DEPENDS "builtin_interfaces" "std_msgs")
set(us_msg_BUILDTOOL_DEPENDS "ament_cmake" "rosidl_default_generators")
set(us_msg_BUILD_EXPORT_DEPENDS "builtin_interfaces" "std_msgs")
set(us_msg_BUILDTOOL_EXPORT_DEPENDS )
set(us_msg_EXEC_DEPENDS "rosidl_default_runtime" "builtin_interfaces" "std_msgs")
set(us_msg_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(us_msg_GROUP_DEPENDS )
set(us_msg_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(us_msg_DEPRECATED "")
set(us_msg_EXPORT_TAGS)
list(APPEND us_msg_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
